name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Build RadiantPi.Lumagen
      - name: Restore dependencies
        run: dotnet restore Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj
      - name: Build
        run: dotnet build --no-restore Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj

      # Build Samples
      - name: Build HelloWorld Sample
        run: dotnet build Samples/HelloWorld/HelloWorld.csproj
      - name: Build Show Mode Info Sample
        run: dotnet build Samples/ShowDisplayMode/ShowDisplayMode.csproj

      # Publish RadiantPi.Lumagen
      - name: Publish
        if: ${{ env.PUSH_PACKAGES }}
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
            PROJECT_FILE_PATH: Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj
            NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
