name: Publish Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj
    - name: Build
      run: dotnet build --no-restore Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj
#    - name: Test
#      run: dotnet test --no-build --verbosity normal Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj
#    - name: Publish
#      uses: brandedoutcast/publish-nuget@v2.5.2
#      with:
#          PROJECT_FILE_PATH: Source/RadiantPi.Lumagen/RadiantPi.Lumagen.csproj
#          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
